server:
  port: 12345
spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.49.180:8848
        username: nacos
        password: nacos
        namespace: 30d2e482-03c0-4181-bf82-99ac00613e20

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always #展示细节，除了always之外还有when-authorized、never，默认值是never
    shutdown:
      enabled: true #开启优雅关机

