server:
  port: 18080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order_route # 标识路由
          uri: http://localhost:8080
          #断言规则
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1
